name: Build and Push Docker image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 체크아웃 코드
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. AWS 자격 증명 설정
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # 3. ECR 로그인
      - name: Log in to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

  
      # 5. Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build --build-arg NEXT_PUBLIC_API_URL="${{ secrets.NEXT_PUBLIC_API_URL }}" \
                       -t 528757801869.dkr.ecr.ap-northeast-2.amazonaws.com/back_container/back_container:latest .
      # 6. Docker 이미지 ECR에 푸시
      - name: Push Docker image to ECR
        run: |
          docker push 528757801869.dkr.ecr.ap-northeast-2.amazonaws.com/back_container/back_container:latest
